<table class="table-schedule mb-3">
    <thead>
    <tr>
        <th>診療時間</th>
        <th>月</th>
        <th>火</th>
        <th>水</th>
        <th>木</th>
        <th>金</th>
        <th>土</th>
        <th>日</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>09:00～12:30</td>
        <td>●</td>
        <td>●</td>
        <td>／</td>
        <td>●</td>
        <td>●</td>
        <td>／</td>
        <td>●</td>
    </tr>
    <tr>
        <td>14:00～18:00</td>
        <td>●</td>
        <td>●</td>
        <td>／</td>
        <td>●</td>
        <td>●</td>
        <td>／</td>
        <td>●</td>
    </tr>
    </tbody>
</table>
<div class="schedule__text text-end">
	<span>休診日：日・祝日</span> ★：土曜は隔週での診療です。
</div>